music_library = {

"happy":[
{"title":"Happy - Pharrell Williams","youtube":"https://www.youtube.com/watch?v=ZbZSe6N_BXs"},
{"title":"Uptown Funk - Bruno Mars","youtube":"https://www.youtube.com/watch?v=OPf0YbXqDm0"},
{"title":"Can't Stop The Feeling - Justin Timberlake","youtube":"https://www.youtube.com/watch?v=ru0K8uYEZWw"},
{"title":"Good Time - Owl City","youtube":"https://www.youtube.com/watch?v=H7HmzwI67ec"},
{"title":"On Top Of The World - Imagine Dragons","youtube":"https://www.youtube.com/watch?v=w5tWYmIOWGk"},
{"title":"Shake It Off - Taylor Swift","youtube":"https://www.youtube.com/watch?v=nfWlot6h_JM"},
{"title":"Sugar - Maroon 5","youtube":"https://www.youtube.com/watch?v=09R8_2nJtjg"},
{"title":"Levitating - Dua Lipa","youtube":"https://www.youtube.com/watch?v=TUVcZfQe-Kw"},
{"title":"Blinding Lights - The Weeknd","youtube":"https://www.youtube.com/watch?v=4NRXx6U8ABQ"},
{"title":"Dance Monkey - Tones and I","youtube":"https://www.youtube.com/watch?v=q0hyYWKXF0Q"},
{"title":"Counting Stars - OneRepublic","youtube":"https://www.youtube.com/watch?v=hT_nvWreIhg"},
{"title":"Best Day Of My Life - American Authors","youtube":"https://www.youtube.com/watch?v=Y66j_BUCBMY"},
{"title":"Thunder - Imagine Dragons","youtube":"https://www.youtube.com/watch?v=fKopy74weus"},
{"title":"Roar - Katy Perry","youtube":"https://www.youtube.com/watch?v=CevxZvSJLk8"},
{"title":"Firework - Katy Perry","youtube":"https://www.youtube.com/watch?v=QGJuMBdaqIw"},
{"title":"I Gotta Feeling - Black Eyed Peas","youtube":"https://www.youtube.com/watch?v=uSD4vsh1zDA"},
{"title":"Senorita - Shawn Mendes","youtube":"https://www.youtube.com/watch?v=Pkh8UtuejGw"},
{"title":"Closer - Chainsmokers","youtube":"https://www.youtube.com/watch?v=PT2_F-1esPk"},
{"title":"Cheap Thrills - Sia","youtube":"https://www.youtube.com/watch?v=nYh-n7EOtMA"},
{"title":"Havana - Camila Cabello","youtube":"https://www.youtube.com/watch?v=HCjNJDNzw8Y"}
],

"sad":[
{"title":"Someone Like You - Adele","youtube":"https://www.youtube.com/watch?v=hLQl3WQQoQ0"},
{"title":"Fix You - Coldplay","youtube":"https://www.youtube.com/watch?v=k4V3Mo61fJM"},
{"title":"Let Her Go - Passenger","youtube":"https://www.youtube.com/watch?v=RBumgq5yVrA"},
{"title":"All I Want - Kodaline","youtube":"https://www.youtube.com/watch?v=mtf7hC17IBM"},
{"title":"Say Something - A Great Big World","youtube":"https://www.youtube.com/watch?v=-2U0Ivkn2Ds"},
{"title":"Hurt - Johnny Cash","youtube":"https://www.youtube.com/watch?v=8AHCfZTRGiI"},
{"title":"The Night We Met","youtube":"https://www.youtube.com/watch?v=KtlgYxa6BMU"},
{"title":"Let Me Down Slowly","youtube":"https://www.youtube.com/watch?v=50VNCymT-Cs"},
{"title":"Arcade - Duncan Laurence","youtube":"https://www.youtube.com/watch?v=51u5fnyrGj4"},
{"title":"Before You Go - Lewis Capaldi","youtube":"https://www.youtube.com/watch?v=Jtauh8GcxBY"},
{"title":"Jealous - Labrinth","youtube":"https://www.youtube.com/watch?v=50VWOBi0VFs"},
{"title":"Stay With Me - Sam Smith","youtube":"https://www.youtube.com/watch?v=pB-5XG-DbAA"},
{"title":"Photograph - Ed Sheeran","youtube":"https://www.youtube.com/watch?v=nSDgHBxUbVQ"},
{"title":"Thinking Out Loud","youtube":"https://www.youtube.com/watch?v=lp-EO5I60KA"},
{"title":"Fix Me - 10 Years","youtube":"https://www.youtube.com/watch?v=V5z5f8Y1WwI"},
{"title":"Chasing Cars - Snow Patrol","youtube":"https://www.youtube.com/watch?v=GemKqzILV4w"},
{"title":"Say You Won't Let Go","youtube":"https://www.youtube.com/watch?v=0yW7w8F2TVA"},
{"title":"Skinny Love","youtube":"https://www.youtube.com/watch?v=ssdgFoHLwnk"},
{"title":"All I Ask - Adele","youtube":"https://www.youtube.com/watch?v=FLSm5Hj4l6g"},
{"title":"Lost Without You","youtube":"https://www.youtube.com/watch?v=9YffrCViTVk"}
],

"neutral":[
{"title":"Let It Be - Beatles","youtube":"https://www.youtube.com/watch?v=QDYfEBY9NM4"},
{"title":"Perfect - Ed Sheeran","youtube":"https://www.youtube.com/watch?v=2Vv-BfVoq4g"},
{"title":"Photograph - Ed Sheeran","youtube":"https://www.youtube.com/watch?v=nSDgHBxUbVQ"},
{"title":"Viva La Vida - Coldplay","youtube":"https://www.youtube.com/watch?v=dvgZkm1xWPE"},
{"title":"Counting Stars","youtube":"https://www.youtube.com/watch?v=hT_nvWreIhg"},
{"title":"Someone You Loved","youtube":"https://www.youtube.com/watch?v=zABLecsR5UE"},
{"title":"Stay - Rihanna","youtube":"https://www.youtube.com/watch?v=JF8BRvqGCNs"},
{"title":"Let Me Love You","youtube":"https://www.youtube.com/watch?v=SMs0GnYze34"},
{"title":"See You Again","youtube":"https://www.youtube.com/watch?v=RgKAFK5djSk"},
{"title":"Faded - Alan Walker","youtube":"https://www.youtube.com/watch?v=60ItHLz5WEA"},
{"title":"Love Yourself","youtube":"https://www.youtube.com/watch?v=oyEuk8j8imI"},
{"title":"Blank Space","youtube":"https://www.youtube.com/watch?v=e-ORhEE9VVg"},
{"title":"What Do You Mean","youtube":"https://www.youtube.com/watch?v=DK_0jXPuIr0"},
{"title":"Stay High","youtube":"https://www.youtube.com/watch?v=SYM-RJwSGQ8"},
{"title":"Counting Stars Remix","youtube":"https://www.youtube.com/watch?v=HcWDLNoqT8U"},
{"title":"Apologize","youtube":"https://www.youtube.com/watch?v=ZSM3w1v-A_Y"},
{"title":"Love Me Like You Do","youtube":"https://www.youtube.com/watch?v=AJtDXIazrMo"},
{"title":"Closer","youtube":"https://www.youtube.com/watch?v=PT2_F-1esPk"},
{"title":"Senorita","youtube":"https://www.youtube.com/watch?v=Pkh8UtuejGw"},
{"title":"Happier","youtube":"https://www.youtube.com/watch?v=m7Bc3pLyij0"}
],

"angry":[
{"title":"Numb - Linkin Park","youtube":"https://www.youtube.com/watch?v=kXYiU_JCYtU"},
{"title":"In The End","youtube":"https://www.youtube.com/watch?v=eVTXPUF4Oz4"},
{"title":"Believer","youtube":"https://www.youtube.com/watch?v=7wtfhZwyrcc"},
{"title":"Radioactive","youtube":"https://www.youtube.com/watch?v=ktvTqknDobU"},
{"title":"Stronger - Kanye West","youtube":"https://www.youtube.com/watch?v=PsO6ZnUZI0g"},
{"title":"Smells Like Teen Spirit","youtube":"https://www.youtube.com/watch?v=hTWKbfoikeg"},
{"title":"Seven Nation Army","youtube":"https://www.youtube.com/watch?v=0J2QdDbelmY"},
{"title":"Bring Me To Life","youtube":"https://www.youtube.com/watch?v=3YxaaGgTQYM"},
{"title":"Breaking The Habit","youtube":"https://www.youtube.com/watch?v=v2H4l9RpkwM"},
{"title":"Enemy - Imagine Dragons","youtube":"https://www.youtube.com/watch?v=D9G1VOjN_84"},
{"title":"DNA - Kendrick Lamar","youtube":"https://www.youtube.com/watch?v=NLZRYQMLDW4"},
{"title":"Lose Yourself","youtube":"https://www.youtube.com/watch?v=_Yhyp-_hX2s"},
{"title":"Till I Collapse","youtube":"https://www.youtube.com/watch?v=ytQ5CYE1VZw"},
{"title":"Rap God","youtube":"https://www.youtube.com/watch?v=XbGs_qK2PQA"},
{"title":"Power - Kanye West","youtube":"https://www.youtube.com/watch?v=L53gjP-TtGE"},
{"title":"Black Skinhead","youtube":"https://www.youtube.com/watch?v=q604eed4ad0"},
{"title":"Monster","youtube":"https://www.youtube.com/watch?v=pS6HRKZQLFA"},
{"title":"Going Under","youtube":"https://www.youtube.com/watch?v=CdhqVtpR2ts"},
{"title":"My Songs Know What You Did","youtube":"https://www.youtube.com/watch?v=LBr7kECsjcQ"},
{"title":"Centuries","youtube":"https://www.youtube.com/watch?v=LBr7kECsjcQ"}
],

"fear":[
{"title":"Boulevard of Broken Dreams","youtube":"https://www.youtube.com/watch?v=Soa3gO7tL-c"},
{"title":"Demons","youtube":"https://www.youtube.com/watch?v=mWRsgZuwf_8"},
{"title":"Creep","youtube":"https://www.youtube.com/watch?v=XFkzRNyygfk"},
{"title":"The Sound Of Silence","youtube":"https://www.youtube.com/watch?v=4fWyzwo1xg0"},
{"title":"Everybody's Fool","youtube":"https://www.youtube.com/watch?v=jhC1pI76Rqo"},
{"title":"My Immortal","youtube":"https://www.youtube.com/watch?v=5anLPw0Efmo"},
{"title":"Haunted","youtube":"https://www.youtube.com/watch?v=3z2s6v9Sg2w"},
{"title":"Hysteria","youtube":"https://www.youtube.com/watch?v=3dm_5qWWDV8"},
{"title":"Bury A Friend","youtube":"https://www.youtube.com/watch?v=HUHC9tYz8ik"},
{"title":"Lovely","youtube":"https://www.youtube.com/watch?v=V1Pl8CzNzCw"},
{"title":"Control","youtube":"https://www.youtube.com/watch?v=so8V5dAli-Q"},
{"title":"Elastic Heart","youtube":"https://www.youtube.com/watch?v=KWZGAExj-es"},
{"title":"Runaway","youtube":"https://www.youtube.com/watch?v=Bm9x9nIYpD0"},
{"title":"Ghost","youtube":"https://www.youtube.com/watch?v=FJt7gNi3Nr4"},
{"title":"Animals","youtube":"https://www.youtube.com/watch?v=qpgTC9MDx1o"},
{"title":"Radioactive Dark Version","youtube":"https://www.youtube.com/watch?v=ktvTqknDobU"},
{"title":"Heathens","youtube":"https://www.youtube.com/watch?v=UprcpdwuwCg"},
{"title":"Bad Guy","youtube":"https://www.youtube.com/watch?v=DyDfgMOUjCI"},
{"title":"Control Halsey","youtube":"https://www.youtube.com/watch?v=so8V5dAli-Q"},
{"title":"Monster Skillet","youtube":"https://www.youtube.com/watch?v=1mjlM_RnsVE"}
],

"disgust":[
{"title":"Numb","youtube":"https://www.youtube.com/watch?v=kXYiU_JCYtU"},
{"title":"Smells Like Teen Spirit","youtube":"https://www.youtube.com/watch?v=hTWKbfoikeg"},
{"title":"Seven Nation Army","youtube":"https://www.youtube.com/watch?v=0J2QdDbelmY"},
{"title":"Bad Guy","youtube":"https://www.youtube.com/watch?v=DyDfgMOUjCI"},
{"title":"Bring Me To Life","youtube":"https://www.youtube.com/watch?v=3YxaaGgTQYM"},
{"title":"Animals","youtube":"https://www.youtube.com/watch?v=qpgTC9MDx1o"},
{"title":"Heathens","youtube":"https://www.youtube.com/watch?v=UprcpdwuwCg"},
{"title":"Control","youtube":"https://www.youtube.com/watch?v=so8V5dAli-Q"},
{"title":"Monster","youtube":"https://www.youtube.com/watch?v=1mjlM_RnsVE"},
{"title":"Going Under","youtube":"https://www.youtube.com/watch?v=CdhqVtpR2ts"},
{"title":"Toxic","youtube":"https://www.youtube.com/watch?v=LOZuxwVk7TU"},
{"title":"Disturbia","youtube":"https://www.youtube.com/watch?v=E1mU6h4Xdxc"},
{"title":"Dark Horse","youtube":"https://www.youtube.com/watch?v=0KSOMA3QBU0"},
{"title":"Black Skinhead","youtube":"https://www.youtube.com/watch?v=q604eed4ad0"},
{"title":"Power","youtube":"https://www.youtube.com/watch?v=L53gjP-TtGE"},
{"title":"Lose Yourself","youtube":"https://www.youtube.com/watch?v=_Yhyp-_hX2s"},
{"title":"Till I Collapse","youtube":"https://www.youtube.com/watch?v=ytQ5CYE1VZw"},
{"title":"Rap God","youtube":"https://www.youtube.com/watch?v=XbGs_qK2PQA"},
{"title":"DNA","youtube":"https://www.youtube.com/watch?v=NLZRYQMLDW4"},
{"title":"Enemy","youtube":"https://www.youtube.com/watch?v=D9G1VOjN_84"}
],

"surprise":[
{"title":"Viva La Vida","youtube":"https://www.youtube.com/watch?v=dvgZkm1xWPE"},
{"title":"Counting Stars","youtube":"https://www.youtube.com/watch?v=hT_nvWreIhg"},
{"title":"Adventure Of A Lifetime","youtube":"https://www.youtube.com/watch?v=QtXby3twMmI"},
{"title":"On Top Of The World","youtube":"https://www.youtube.com/watch?v=w5tWYmIOWGk"},
{"title":"Thunder","youtube":"https://www.youtube.com/watch?v=fKopy74weus"},
{"title":"Blinding Lights","youtube":"https://www.youtube.com/watch?v=4NRXx6U8ABQ"},
{"title":"Levitating","youtube":"https://www.youtube.com/watch?v=TUVcZfQe-Kw"},
{"title":"Uptown Funk","youtube":"https://www.youtube.com/watch?v=OPf0YbXqDm0"},
{"title":"Dance Monkey","youtube":"https://www.youtube.com/watch?v=q0hyYWKXF0Q"},
{"title":"Closer","youtube":"https://www.youtube.com/watch?v=PT2_F-1esPk"},
{"title":"Cheap Thrills","youtube":"https://www.youtube.com/watch?v=nYh-n7EOtMA"},
{"title":"Havana","youtube":"https://www.youtube.com/watch?v=HCjNJDNzw8Y"},
{"title":"Roar","youtube":"https://www.youtube.com/watch?v=CevxZvSJLk8"},
{"title":"Firework","youtube":"https://www.youtube.com/watch?v=QGJuMBdaqIw"},
{"title":"Good Time","youtube":"https://www.youtube.com/watch?v=H7HmzwI67ec"},
{"title":"Best Day Of My Life","youtube":"https://www.youtube.com/watch?v=Y66j_BUCBMY"},
{"title":"Senorita","youtube":"https://www.youtube.com/watch?v=Pkh8UtuejGw"},
{"title":"Perfect","youtube":"https://www.youtube.com/watch?v=2Vv-BfVoq4g"},
{"title":"Photograph","youtube":"https://www.youtube.com/watch?v=nSDgHBxUbVQ"},
{"title":"Happier","youtube":"https://www.youtube.com/watch?v=m7Bc3pLyij0"}
],

"calm":[
{"title":"Weightless - Marconi Union","youtube":"https://www.youtube.com/watch?v=UfcAVejslrU"},
{"title":"Clair de Lune - Debussy","youtube":"https://www.youtube.com/watch?v=CvFH_6DNRCY"},
{"title":"River Flows In You - Yiruma","youtube":"https://www.youtube.com/watch?v=7maJOI3QMu0"},
{"title":"Experience - Ludovico Einaudi","youtube":"https://www.youtube.com/watch?v=_VONMkKkdf4"},
{"title":"Let Her Go - Passenger","youtube":"https://www.youtube.com/watch?v=RBumgq5yVrA"},
{"title":"Fix You - Coldplay","youtube":"https://www.youtube.com/watch?v=k4V3Mo61fJM"},
{"title":"Perfect - Ed Sheeran","youtube":"https://www.youtube.com/watch?v=2Vv-BfVoq4g"},
{"title":"Stay - Rihanna","youtube":"https://www.youtube.com/watch?v=JF8BRvqGCNs"},
{"title":"All I Want - Kodaline","youtube":"https://www.youtube.com/watch?v=mtf7hC17IBM"},
{"title":"Turning Page - Sleeping At Last","youtube":"https://www.youtube.com/watch?v=ttMY4t4P9K0"},
{"title":"Holocene - Bon Iver","youtube":"https://www.youtube.com/watch?v=TWcyIpul8OE"},
{"title":"Bloom - The Paper Kites","youtube":"https://www.youtube.com/watch?v=8inJtTG_DuU"},
{"title":"Skinny Love - Birdy","youtube":"https://www.youtube.com/watch?v=aNzCDt2eidg"},
{"title":"Someone Like You - Adele","youtube":"https://www.youtube.com/watch?v=hLQl3WQQoQ0"},
{"title":"Say You Won't Let Go - James Arthur","youtube":"https://www.youtube.com/watch?v=0yW7w8F2TVA"},
{"title":"Photograph - Ed Sheeran","youtube":"https://www.youtube.com/watch?v=nSDgHBxUbVQ"},
{"title":"Let It Be - Beatles","youtube":"https://www.youtube.com/watch?v=QDYfEBY9NM4"},
{"title":"Apologize - OneRepublic","youtube":"https://www.youtube.com/watch?v=ZSM3w1v-A_Y"},
{"title":"Happier - Marshmello","youtube":"https://www.youtube.com/watch?v=m7Bc3pLyij0"},
{"title":"Sunflower - Post Malone","youtube":"https://www.youtube.com/watch?v=ApXoWvfEYVU"}
],

}